server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e3mall?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: "root"
  dubbo:
    registry:
      protocol: zookeeper
      address: 192.168.25.129:2181
    application:
      name: account-server
    protocol:
      name: dubbo
      port: 20880
  redis:
    host: 127.0.0.1
    port: 6379
    password: kong
    timeout: 2000
    database: 0
mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
