server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.139.244:3306/lanbomkong?autoReconnect=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: "root"
  dubbo:
    registry:
      protocol: zookeeper
      address: 106.12.139.244:2181
    application:
      name: account-server
    protocol:
      name: dubbo
      port: 20880
  redis:
#    cluster:
#      nodes:
#        - 192.168.25.134:7001
#        - 192.168.25.134:7002
#        - 192.168.25.134:7003
#        - 192.168.25.134:7004
#        - 192.168.25.134:7005
#        - 192.168.25.134:7006
    host: 106.12.139.244
    port: 6379
    password: kong
    timeout: 2000
    database: 0
  rabbitmq:
    host: 106.12.139.244
    port: 5672
    username: admin
    password: admin
mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl